controller_list:
  - name: ""
#    action_ns: robot0/joint_trajectory_action
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
